name: Flutter CI

on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'
      - run: sh setEnv.sh ${{ secrets.FIREBASEAPIKEY }} ${{ secrets.MAPSURL }} ${{ secrets.FIREBASECONFIG }}
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web
      - uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: build/web/
      
      
